apiVersion: v1
kind: Pod
metadata:
  name: dolly-gpu-1
  # labels:
  #   # any Pods with matching labels are included in this Daemon Set
  #   app: kubernetes-series
  #   tier: monitor
spec:
  containers:
  - name: dolly-gpu
    image: docker.io/cford38/dolly-v2-3b-azurefunction:latest-anon
    ports:
    - containerPort: 80
    command: ["sleep", "infinity"]
    resources:
      limits:
       nvidia.com/gpu: 1
  tolerations:
  - key: "sku"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
  nodeSelector:
    agentpool: dollywood
